### ISSUE TITLE
2.11.2 broke Java 7 compatibility

### ISSUE THREAD

**Issue by ajburley** [srikanth-lingala/zip4j#492]
2.11.1 was working with Java 7, but after upgrading to 2.11.2 or 2.11.3, it crashes

```
    java.lang.NoSuchMethodError: No virtual method toPath()Ljava/nio/file/Path; in class Ljava/io/File; or its super classes (declaration of 'java.io.File' appears in /system/framework/core-libart.jar)
        at net.lingala.zip4j.util.FileUtils.getRelativeFileName(FileUtils.java:225)
        at net.lingala.zip4j.tasks.AbstractAddFileToZipTask.cloneAndAdjustZipParameters(AbstractAddFileToZipTask.java:218)
        at net.lingala.zip4j.tasks.AbstractAddFileToZipTask.addFilesToZip(AbstractAddFileToZipTask.java:71)
        at net.lingala.zip4j.tasks.AddFolderToZipTask.executeTask(AddFolderToZipTask.java:28)
        at net.lingala.zip4j.tasks.AddFolderToZipTask.executeTask(AddFolderToZipTask.java:17)
        at net.lingala.zip4j.tasks.AsyncZipTask.performTaskWithErrorHandling(AsyncZipTask.java:51)
        at net.lingala.zip4j.tasks.AsyncZipTask.execute(AsyncZipTask.java:45)
        at net.lingala.zip4j.ZipFile.addFolder(ZipFile.java:391)
        at net.lingala.zip4j.ZipFile.addFolder(ZipFile.java:366)
        at com.mycompany.ZipService.zipFolder(ZipService.kt:21)
```

I need to support Java 7 because a lot of my users are on Android 5 which is based on Java 7.

**Comment by srikanth-lingala** [comment]
Try using v2.11.4. This issue was fixed in this version.

**Comment by ajburley** [comment]
@srikanth-lingala thanks, 2.11.4 fixed it

Strangely, 2.11.3 is still listed as the "latest" version on your homepage https://github.com/srikanth-lingala/zip4j - so I didn't even realise there was a 2.11.4
