### ISSUE TITLE
Crash on Android Nougat (7.x) and below due to lack of java.nio.file APIs not added until Android 8.0 Oreo

### ISSUE THREAD

**Issue by dknchris** [srikanth-lingala/zip4j#4]
Hi, thanks for your work!

java.nio.file APIs were added to Android with API 26 (8.0, Oreo). Thus, zip4j v2.0 will work only on Android 8.0 and up for Android devices.  Is this API choice? Many wouldn't be able to use the new version on Android, since Android 6.0 Marshmallow and 7.x Nougat are still supported by many apps.

`--------- beginning of crash
06-26 10:35:07.660 4977-5149/org.swiftapps.swiftbackup E/AndroidRuntime: FATAL EXCEPTION: IntentService[TaskService]
    Process: org.swiftapps.swiftbackup, PID: 4977
    java.lang.NoSuchMethodError: No virtual method toPath()Ljava/nio/file/Path; in class Ljava/io/File; or its super classes (declaration of 'java.io.File' appears in /system/framework/core-libart.jar)
        at net.lingala.zip4j.tasks.AbstractAddFileToZipTask.addFilesToZip(AbstractAddFileToZipTask.java:78)
        at net.lingala.zip4j.tasks.AddFolderToZipTask.executeTask(AddFolderToZipTask.java:28)
        at net.lingala.zip4j.tasks.AddFolderToZipTask.executeTask(AddFolderToZipTask.java:16)
        at net.lingala.zip4j.tasks.AsyncZipTask.performTaskWithErrorHandling(AsyncZipTask.java:40)
        at net.lingala.zip4j.tasks.AsyncZipTask.execute(AsyncZipTask.java:34)
        at net.lingala.zip4j.ZipFile.addFolder(ZipFile.java:359)
        at net.lingala.zip4j.ZipFile.addFolder(ZipFile.java:334)
        at org.swiftapps.swiftbackup.common.Zipper.packFoldersZip4J(Zipper.kt:96)
        at org.swiftapps.swiftbackup.common.Zipper.packFolders(Zipper.kt:22)
        at org.swiftapps.swiftbackup.apptasks.AppBackupTask.packFoldersToZip(AppBackupTask.kt:508)
        at org.swiftapps.swiftbackup.apptasks.AppBackupTask.execute(AppBackupTask.kt:266)
        at org.swiftapps.swiftbackup.apptasks.AppBackupManager.processApp(AppBackupManager.kt:80)
        at org.swiftapps.swiftbackup.apptasks.AppBackupManager.execute(AppBackupManager.kt:65)
        at org.swiftapps.swiftbackup.tasks.stasks.AppsTask.startBackup(AppsTask.kt:117)
        at org.swiftapps.swiftbackup.tasks.stasks.AppsTask.executeTask(AppsTask.kt:80)
        at org.swiftapps.swiftbackup.tasks.stasks.STask.execute(STask.kt:83)
        at org.swiftapps.swiftbackup.tasks.TaskManager.performTasks(TaskManager.kt:104)
        at org.swiftapps.swiftbackup.tasks.TaskService.onHandleIntent(TaskService.kt:33)
        at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:66)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:148)
        at android.os.HandlerThread.run(HandlerThread.java:61)`

**Comment by srikanth-lingala** [comment]
I can add some logic to skip that part of the code if NIO is not present/supported.

Without NIO it will be pretty hard to get file attributes. So when zipping files, file attributes cannot be determined and added to zip headers. The result of this will be that when those files are unzipped, all the files will be with (system) default file attributes. 

But obviously this is better than just crashing. I will make a snapshot release, and update this issue. It would be great if you can test with that version and let me know if it works. Thanks.

**Comment by srikanth-lingala** [comment]
Snapshot version `2.0.1-SNAPSHOT` is now pushed. Can you please try with it and let me know if this fixes it? Thanks. You have to have [snapshot repository configured in your maven settings][1].

[1]: https://stackoverflow.com/a/7717234/2736153

**Comment by dknchris** [comment]
> 2.0.1-SNAPSHOT

Can confirm this works. Thanks for the quick response and the snapshot build! zip4j is very integral to my project. Thank you for your work again.

**Comment by nicolabeghin** [comment]
Following, extremely interested!

**Comment by srikanth-lingala** [comment]
@nicolabeghin This issue is fixed already in v2.0.1. I just made a release v2.0.3 with a few more fixes. I just pushed this release to maven, it takes a few hours for the sync. In the mean time you can use v2.0.2 which has this fix and is available on maven. But once v2.0.3 is available on maven, I highly recommend to upgrade to that version.

**Comment by nicolabeghin** [comment]
For anyone moving to zip4j-2 on Android, add this in build.gradle
ref. https://developer.android.com/studio/write/java8-support.html

     compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
     }

I'm not sure `stream` are supported in Android API before 24, but I just tested it as working on an Android 5.1. ref. https://developer.android.com/studio/write/java8-support.html#supported_features

**Comment by choiman1559** [comment]
Hello, Thanks for your work!

```List.sort``` APIs were added to Android with API 26 (8.0, Oreo). Thus, latest version of zip4j will work only on Android 8.0 and up for Android devices. Is there any solution for it? I need Android 7 or lower support to develop and maintain my app, but this problem makes it impossible.

+ And also I got these exceptions even though I added Java 1.8 support to my app.

```
Caused by java.lang.NoSuchMethodError: No interface method sort(Ljava/util/Comparator;)V in class Ljava/util/List; or its super classes (declaration of 'java.util.List' appears in /system/framework/core-libart.jar)
       at net.lingala.zip4j.tasks.AbstractModifyFileTask.cloneAndSortFileHeadersByOffset(AbstractModifyFileTask.java:76)
       at net.lingala.zip4j.tasks.RemoveFilesFromZipTask.executeTask(RemoveFilesFromZipTask.java:52)
       at net.lingala.zip4j.tasks.RemoveFilesFromZipTask.executeTask(RemoveFilesFromZipTask.java:21)
       at net.lingala.zip4j.tasks.AsyncZipTask.performTaskWithErrorHandling(AsyncZipTask.java:46)
       at net.lingala.zip4j.tasks.AsyncZipTask.execute(AsyncZipTask.java:40)
       at net.lingala.zip4j.tasks.AbstractAddFileToZipTask.removeFile(AbstractAddFileToZipTask.java:266)
       at net.lingala.zip4j.tasks.AbstractAddFileToZipTask.removeFilesIfExists(AbstractAddFileToZipTask.java:251)
       at net.lingala.zip4j.tasks.AbstractAddFileToZipTask.addFilesToZip(AbstractAddFileToZipTask.java:64)
       at net.lingala.zip4j.tasks.AddFolderToZipTask.executeTask(AddFolderToZipTask.java:28)
       at net.lingala.zip4j.tasks.AddFolderToZipTask.executeTask(AddFolderToZipTask.java:17)
       at net.lingala.zip4j.tasks.AsyncZipTask.performTaskWithErrorHandling(AsyncZipTask.java:46)
       at net.lingala.zip4j.tasks.AsyncZipTask.execute(AsyncZipTask.java:40)
       at net.lingala.zip4j.ZipFile.addFolder(ZipFile.java:364)
       at net.lingala.zip4j.ZipFile.addFolder(ZipFile.java:339)
       at com.fqxd.gftools.features.decom.PatchTask.doInBackground(PatchTask.java:130)
       at com.fqxd.gftools.implement.AsyncTask$3.call(AsyncTask.java:223)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at com.fqxd.gftools.implement.AsyncTask$SerialExecutor.lambda$execute$0$AsyncTask$SerialExecutor(AsyncTask.java:136)
       at com.fqxd.gftools.implement.-$$Lambda$AsyncTask$SerialExecutor$FGB3Rik2507exmLqsfc4mPQNB68.run(lambda)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:818)
       ```

**Comment by srikanth-lingala** [comment]
@choiman1559 Can you please open a new issue?
