### ISSUE TITLE
Crash with 2.4.0 in Android

### ISSUE THREAD

**Issue by johanw666** [srikanth-lingala/zip4j#156]
I use zip4j some time now in my Android project (https://github.com/johanw666/Signal-Android), but since I upgraded to 2.4.0 I get a crash. Reverting back to 2.3.2 fixed it.
```
03-08 05:42:02.518 13951 18215 E AndroidRuntime: FATAL EXCEPTION: AsyncTask #2
03-08 05:42:02.518 13951 18215 E AndroidRuntime: Process: org.thoughtcrime.securesms, PID: 13951
03-08 05:42:02.518 13951 18215 E AndroidRuntime: java.lang.RuntimeException: An error occurred while executing doInBackground()
03-08 05:42:02.518 13951 18215 E AndroidRuntime: 	at android.os.AsyncTask$3.done(AsyncTask.java:309)
03-08 05:42:02.518 13951 18215 E AndroidRuntime: 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
03-08 05:42:02.518 13951 18215 E AndroidRuntime: 	at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
03-08 05:42:02.518 13951 18215 E AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:242)
03-08 05:42:02.518 13951 18215 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
03-08 05:42:02.518 13951 18215 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
03-08 05:42:02.518 13951 18215 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:818)
03-08 05:42:02.518 13951 18215 E AndroidRuntime: Caused by: java.lang.NoSuchMethodError: No virtual method toPath()Ljava/nio/file/Path; in class Ljava/io/File; or its super classes (declaration of 'java.io.File' appears in /system/framework/core-libart.jar)
03-08 05:42:02.518 13951 18215 E AndroidRuntime: 	at net.lingala.zip4j.util.FileUtils.getRelativeFileName(FileUtils.java:211)
03-08 05:42:02.518 13951 18215 E AndroidRuntime: 	at net.lingala.zip4j.tasks.AbstractAddFileToZipTask.cloneAndAdjustZipParameters(AbstractAddFileToZipTask.java:215)
03-08 05:42:02.518 13951 18215 E AndroidRuntime: 	at net.lingala.zip4j.tasks.AbstractAddFileToZipTask.addFilesToZip(AbstractAddFileToZipTask.java:70)
03-08 05:42:02.518 13951 18215 E AndroidRuntime: 	at net.lingala.zip4j.tasks.AddFolderToZipTask.executeTask(AddFolderToZipTask.java:28)
03-08 05:42:02.518 13951 18215 E AndroidRuntime: 	at net.lingala.zip4j.tasks.AddFolderToZipTask.executeTask(AddFolderToZipTask.java:17)
03-08 05:42:02.518 13951 18215 E AndroidRuntime: 	at net.lingala.zip4j.tasks.AsyncZipTask.performTaskWithErrorHandling(AsyncZipTask.java:44)
03-08 05:42:02.518 13951 18215 E AndroidRuntime: 	at net.lingala.zip4j.tasks.AsyncZipTask.execute(AsyncZipTask.java:38)
03-08 05:42:02.518 13951 18215 E AndroidRuntime: 	at net.lingala.zip4j.ZipFile.addFolder(ZipFile.java:377)
03-08 05:42:02.518 13951 18215 E AndroidRuntime: 	at net.lingala.zip4j.ZipFile.addFolder(ZipFile.java:352)
03-08 05:42:02.518 13951 18215 E AndroidRuntime: 	at org.thoughtcrime.securesms.database.EncryptedBackupExporter.createEncryptedZipfile(EncryptedBackupExporter.java:459)
03-08 05:42:02.518 13951 18215 E AndroidRuntime: 	at org.thoughtcrime.securesms.database.EncryptedBackupExporter.exportToSd(EncryptedBackupExporter.java:85)
03-08 05:42:02.518 13951 18215 E AndroidRuntime: 	at org.thoughtcrime.securesms.ImportExportFragment$ExportEncryptedTask.doInBackground(ImportExportFragment.java:403)
03-08 05:42:02.518 13951 18215 E AndroidRuntime: 	at org.thoughtcrime.securesms.ImportExportFragment$ExportEncryptedTask.doInBackground(ImportExportFragment.java:362)
03-08 05:42:02.518 13951 18215 E AndroidRuntime: 	at android.os.AsyncTask$2.call(AsyncTask.java:295)
03-08 05:42:02.518 13951 18215 E AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
03-08 05:42:02.518 13951 18215 E AndroidRuntime: 	... 3 more
```
(full debug log at https://debuglogs.org/e78b2f9e04bd7447440ab1b7334a4e13d139fcf2a03e137e5f5b67922b3439e0 ).

This is the code I use to create a zipfile:
```java
  // Handle backups in encrypted zipfiles
  private static boolean createEncryptedZipfile(Context context) {
    try {
      String password = getBackupPassword(context);
      ZipFile zipFile = new ZipFile(getEncryptedZipfileName());
      ZipParameters parameters = new ZipParameters();
      parameters.setCompressionMethod(CompressionMethod.STORE); // Encrypted data is uncompressable anyway
      //parameters.setCompressionLevel(CompressionLevel.FASTEST);
      if (password.length() > 0 ) {
        parameters.setEncryptFiles(true);
        parameters.setEncryptionMethod(EncryptionMethod.AES);
        parameters.setAesKeyStrength(AesKeyStrength.KEY_STRENGTH_256);
        zipFile.setPassword(password.toCharArray());
      }
      zipFile.addFolder(new File(getExportSecretsDirectory(context)), parameters);
      zipFile.addFolder(new File(getExportDirectoryPath(context)), parameters);
    } catch (ZipException e) {
      Log.w(TAG, "createEncryptedZipfile failed: " + e.toString());
      return false;
    }
    return true;
  }
```

**Comment by srikanth-lingala** [comment]
This issue has been reported in #148 and is fixed. There is snapshot version currently with the fix `2.4.1-SNAPSHOT`.  I will make a final release in the next few hours.

**Comment by srikanth-lingala** [comment]
Fix included in v2.5.0 released today. A couple of more features have been added in this release. Please have a look at [release notes][1].

[1]: https://github.com/srikanth-lingala/zip4j/releases
